import 'package:flutter/material.dart';
import 'package:test_oatmeal/controllers/color_generator.dart';

/// Main page of the app where colors are being generated.
class HomePage extends StatefulWidget {
  /// Creates home page where colors are being generated.
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  double fontSize = 16.0;
  double luminanceValue = 0.5;

  ColorGenerator generator = ColorGenerator();

  void _colorGenerator() {
    setState(() {
      generator.generateColor();
    });
  }

  /// Creates home page with background colors generated by tapping anywhere
  /// on the screen.
  ///
  /// Background brightness gets computed before assigning text color to
  /// guarantee readability.
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: InkWell(
        onTap: _colorGenerator,
        child: Center(
          child: Text(
            "Hey there",
            style: TextStyle(
              fontSize: fontSize,
              fontWeight: FontWeight.bold,
              color: generator.currentColor.computeLuminance() > luminanceValue
                  ? Colors.black
                  : Colors.white,
            ),
          ),
        ),
      ),
      backgroundColor: generator.currentColor,
    );
  }
}
